"""table configured

Revision ID: f3add73be8ef
Revises: 
Create Date: 2025-04-19 17:32:06.489924

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3add73be8ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CERTIFICADO_FACTURA',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cae', sa.String(length=255), nullable=True),
    sa.Column('certificado', sa.Text(), nullable=True),
    sa.Column('factura', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('certificado_factura')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificado_factura',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cae', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('certificado', mysql.TEXT(), nullable=True),
    sa.Column('factura', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('CERTIFICADO_FACTURA')
    # ### end Alembic commands ###
